### Rgister:
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "test552@example.com",
  "password": "password123"
}

### Login:
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "test552@example.com",
  "password": "password123"
}

### Get user:
GET {{host}}/users/me
Content-Type: application/json

### Logout:
POST {{host}}/auth/logout
Content-Type: application/json

### Get Notes:
GET {{host}}/notes
Content-Type: application/json

### Add note:
POST {{host}}/notes
Content-Type: application/json

{
  "title": "Learn next.js",
  "content": "Route handlers",
  "tag": "Important"
}

### Update user:
PATCH {{host}}/users/me
Content-Type: application/json

{
  "email": "test552@example.com",
  "username": "username@mail.com"
}